### ISSUE TITLE
[Request] Your bot needs a fuck option!!!

### ISSUE THREAD

**Issue by backas** [doamatto/swiftbot#1]
Dear. Doamatto.

Your bot has many good abilities my favorite are the hug and table flip, sometimes the kiss if i'm feeling it.
My request is that you add a fuck option please, we all know we want this option because the kiss sometimes just isn't enough.

Kind regards,
backas

**Comment by doamatto** [comment]
Thanks Backas (🍞)! I'll look into it. Considering the nature of such, this command may be restricted to only channels noted as NSFW.

**Comment by doamatto** [comment]
A card has been made, when I get the chance; I'll work on it soon™. (that card is [here](https://trello.com/c/qcrHs5Mj/23-fuck-command))
