### ISSUE TITLE
i would like to help with development

### ISSUE THREAD

**Issue by calebrwalk5** [doamatto/swiftbot#52]
yo can i help with development? check out my repositories and determine my skill level for yourself

**Comment by doamatto** [comment]
Hey @calebrwalk5, I plan to re-write the entire bot in either Rust or Golang (leaning towards Rust as I've had more experience with it) once I get some free time. If that sounds good to you, then feel free to make PRs from the issues once the Rust branch is established.

**Comment by calebrwalk5** [comment]
> Hey @calebrwalk5, I plan to re-write the entire bot in either Rust or Golang (leaning towards Rust as I've had more experience with it) once I get some free time. If that sounds good to you, then feel free to make PRs from the issues once the Rust branch is established.

sorry man, I don't know rust or go
